#!/usr/bin/env python3
"""Generate per-heater HA packages from a roster JSON.

    python3 gen_packages.py --input heaters.prod.json --out <config>/packages

The roster is the source of truth for the heaters; the YAML is a build artifact
(regenerated by push.sh for the prod box and by the container entrypoint for
dev/demo — one roster per environment). One file per heater, `<id>.yaml`.

Each entry:
    id                        entity base — MUST be `heater_<n>` (the SPA and the
                              scheduling package key off `switch.heater_*` /
                              `input_boolean.heater_*`)
    label                     friendly name shown in the UI
    duration                  auto-off window: HH:MM:SS, or 3h / 90m (default 2h)
    simulated                 true → input_boolean + fake power; false/absent →
                              real switch (device provides switch.<id> + power)
    simulated_power_initial   simulated watts (simulated only, default 1200)
    icon                      input_boolean icon (simulated only, default radiator)
    switch                    real switch entity (real only, default switch.<id>)

stdlib only (runs on the operator's machine and in the container).
"""
import argparse
import json
import os
import re


def _duration(d):
    d = str(d).strip()
    if re.fullmatch(r"\d{1,2}:\d{2}:\d{2}", d):
        return d
    m = re.fullmatch(r"(\d+)h", d)
    if m:
        return f"{int(m.group(1)):02d}:00:00"
    m = re.fullmatch(r"(\d+)m", d)
    if m:
        n = int(m.group(1))
        return f"{n // 60:02d}:{n % 60:02d}:00"
    raise SystemExit(f"[gen] bad duration {d!r} (want HH:MM:SS, 3h, or 90m)")


def _yq(s):
    """Quote a string for a double-quoted YAML scalar."""
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def render(h):
    hid = h["id"]
    if not re.fullmatch(r"heater_[a-z0-9_]+", hid):
        raise SystemExit(f"[gen] id {hid!r} must match heater_<n> (SPA convention)")
    label = h["label"]
    duration = _duration(h.get("duration", "02:00:00"))
    switch = h.get("switch", f"switch.{hid}")
    simulated = bool(h.get("simulated", False))
    toggle = f"input_boolean.{hid}" if simulated else switch

    blocks = []
    if simulated:
        blocks.append(
            f"input_boolean:\n"
            f"  {hid}:\n"
            f"    name: {_yq(label)}\n"
            f"    icon: {h.get('icon', 'mdi:radiator')}\n"
        )
    blocks.append(
        f"timer:\n"
        f"  {hid}_autooff:\n"
        f'    duration: "{duration}"\n'
        f"    restore: true\n"
    )
    blocks.append(
        f"automation:\n"
        f"  - alias: {_yq(f'{label}: auto-off wiring')}\n"
        f"    use_blueprint:\n"
        f"      path: heater_control/switch_with_auto_off.yaml\n"
        f"      input:\n"
        f"        switch: {toggle}\n"
        f"        autooff_timer: timer.{hid}_autooff\n"
    )
    if simulated:
        watts = int(h.get("simulated_power_initial", 1200))
        blocks.append(
            f"input_number:\n"
            f"  {hid}_simulated_watts:\n"
            f"    name: {_yq(f'{label} simulated wattage')}\n"
            f"    min: 0\n"
            f"    max: 2000\n"
            f"    step: 100\n"
            f"    initial: {watts}\n"
            f'    unit_of_measurement: "W"\n'
            f"    icon: mdi:flash\n"
        )
        blocks.append(
            f"template:\n"
            f"  - sensor:\n"
            f"      - name: {_yq(f'{label} power')}\n"
            f"        unique_id: {hid}_power\n"
            f'        unit_of_measurement: "W"\n'
            f"        device_class: power\n"
            f"        state: >\n"
            f"          {{% if is_state('input_boolean.{hid}', 'on') %}}\n"
            f"            {{{{ states('input_number.{hid}_simulated_watts') | float(0) }}}}\n"
            f"          {{% else %}}\n"
            f"            0\n"
            f"          {{% endif %}}\n"
        )
    else:
        # Real switch: the device provides switch.<id> + its power sensor; we only
        # add the timer + auto-off wiring, and override the switch's display name.
        blocks.append(
            f"homeassistant:\n"
            f"  customize:\n"
            f"    {switch}:\n"
            f"      friendly_name: {_yq(label)}\n"
        )
    return "\n".join(blocks)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input", required=True, help="roster JSON")
    ap.add_argument("--out", required=True, help="output packages dir")
    args = ap.parse_args()

    with open(args.input) as f:
        roster = json.load(f)
    os.makedirs(args.out, exist_ok=True)

    seen = set()
    for h in roster:
        hid = h["id"]
        if hid in seen:
            raise SystemExit(f"[gen] duplicate id {hid!r}")
        seen.add(hid)
        with open(os.path.join(args.out, f"{hid}.yaml"), "w") as f:
            f.write(render(h))
    print(f"[gen] wrote {len(roster)} heater package(s) to {args.out}")


if __name__ == "__main__":
    main()
